#!/usr/bin/env bash
# kubecm is a utitilty to manage and merge KUBECONFIG environment for IBM kubernertes service
# to use kubectx(https://github.com/ahmetb/kubectx) easily

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
  cat <<"EOF"
USAGE:
  kubecm                       : print current KUBECONFIG 
  kubecm -r                    : reload KUBECONFIG

  kubecm -h,--help             : show this message
EOF
}

reload() {
  echo "Start reloading KUBECONFIG"
  cat > /tmp/kube-config-dummy-${TERM_SESSION_ID##*:}.yml <<EOF
apiVersion: v1
clusters:
- cluster:
    server: ""
  name: dummy
contexts:
- context:
    cluster: ""
    user: ""
  name: dummy
current-context: dummy
kind: Config
preferences: {}
users:
- name: dummy
  user: {}
EOF

  export KUBECONFIG="/tmp/kube-config-dummy-${TERM_SESSION_ID##*:}.yml:$(find ~/.bluemix/plugins/container-service/clusters -path '*/*-admin/kube-config-*.yml' -exec bash -c 'cluster_name=`yq r $0 clusters[0].name`; yq w -i $0 contexts[0].context.user $cluster_name; yq w -i $0 users[0].name $cluster_name; echo $0' {} \; | tr '\n' ':')"
  echo "End reloading KUBECONFIG"
  echo $KUBECONFIG
}

main() {
  if [[ "$#" -eq 0 ]]; then
    echo $KUBECONFIG
  elif [[ "$#" -eq 1 ]]; then
    if [[ "${1}" == "-r" ]]; then
      reload
    elif [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
      usage
    fi
  else
    usage
    exit 1
  fi
}

main "$@"
